### ISSUE TITLE
Cameron Browne can't receive the Activation Code from your forum.

### ISSUE THREAD

**Issue by yuandj** [Ludeme/LudiiAICompetition#1]
https://ludii.games/forums/newreply.php?tid=407&replyto=1862

I'm using  (Resend Activation Code) https://ludii.games/forums/member.php?action=resendactivation

my user name is same as github.

I'll trying to orgnazing my students to join the competation this year.

**Comment by stepmat** [comment]
Hi,

I've just activated your account on the Ludii forum, sometimes the activation code email gets marked as spam by some email providers...

Its great to hear that you are interested in participating in our competition!

**Comment by yuandj** [comment]
![image](https://user-images.githubusercontent.com/14815502/108620490-78ad2a00-7467-11eb-89bb-65e9a24a701c.png)

weldone. :D
